# Generated by Django 5.0.6 on 2024-05-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticky_notes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickynote',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
