# Generated by Django 5.0.6 on 2024-06-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sticky_notes_app', '0002_stickynote_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stickynote',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
